[server]
port = 8501
headless = true
runOnSave = true
enableXsrfProtection = false
enableCORS = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[theme]
primaryColor = "#00d09c"
backgroundColor = "#121212"
secondaryBackgroundColor = "#1E1E1E"
textColor = "#FFFFFF"
font = "sans serif"
